services:
  - type: web
    name: disabledassistnetwork-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: FIREBASE_PROJECT_ID
        value: disabledassistnetwork
      - key: FIREBASE_SERVICE_ACCOUNT
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: CLOUDINARY_URL
        sync: false
      - key: FAST2SMS_API_KEY
        sync: false
